apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: pumajosleaa/auth
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service:27017/chatapp"
